# Generated by Django 3.2.8 on 2021-11-29 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('ERR', 'Error'), ('OFF', 'Offline'), ('ON', 'In Service')], default='ON', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('display_name', models.CharField(max_length=64)),
                ('adress', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('ERR', 'Error'), ('OFF', 'Offline'), ('ON', 'In Service')], default='ON', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=32)),
                ('false_positives', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reference', models.CharField(default='Smartphone', max_length=50)),
                ('physical_state', models.CharField(max_length=64)),
                ('software_diagnostic', models.CharField(max_length=64)),
                ('comment', models.CharField(max_length=256)),
                ('locker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='framework.locker')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='framework.terminal')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateTimeField(verbose_name='Date de la mission')),
                ('state', models.CharField(choices=[('IQ', 'In Queue'), ('PA', 'Paused'), ('NA', 'Not Attributed'), ('CF', 'Conflict'), ('AR', 'Archived'), ('FA', 'Failed'), ('IP', 'In Process'), ('CO', 'Completed')], default='NA', max_length=2)),
                ('false_positives', models.IntegerField(default=0)),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='framework.technician')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='framework.terminal')),
            ],
        ),
        migrations.AddField(
            model_name='locker',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='framework.terminal'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('DE', 'Deposit'), ('VA', 'Validated'), ('WI', 'Withdrawal'), ('NA', 'Not Assessed')], default='NA', max_length=2)),
                ('state', models.CharField(choices=[('IT', 'In Transit'), ('DO', 'Done'), ('ER', 'Error'), ('WA', 'Waiting')], default='WA', max_length=2)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='framework.mission')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='framework.product')),
            ],
        ),
    ]
